<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="/css/main.css">
</head>
<body>

	<div class="container">
		<div class="list-header">
			<h2>
				<a href="/lists" class="backarrow">&mapstoleft;</a>
				<?= $list->getListName(); ?>
			</h2>
		</div>

		<form action="/list/<?= $list->getId(); ?>/add" method="POST">
			<!-- CSRF field -->
			<input type="text" class="list-input" name="new-item" id="new-item" autofocus autocomplete="off">
		</form>

	<?php foreach($list->getItems() as $item): ?>
		<?php if ( $item->isActive() ): ?>
		<div class="list-element item-complete">
			<a href="/item/<?= $item->getId(); ?>/deactivate" class="btn btn-left item-check-btn">on</a>
		<?php else: ?>
		<div class="list-element">
			<a href="/item/<?= $item->getId(); ?>/activate" class="btn btn-left item-check-btn">off</a>
		<?php endif; ?>
			<span class="list-details">
				<span class="list-name"><?= $item->getValue(); ?></span>
				<span class="list-created">Created: <?= $item->getCreated(); ?></span>
				<span class="list-updated">Updated: <?= $item->getUpdated(); ?></span>
			</span>
			<a href="/item/<?= $item->getId(); ?>/edit" class="btn item-edit-btn">&vellip;</a>
		</div>
	<?php endforeach; ?>
	</div>

</body>
</html>