<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="/css/main.css">
</head>
<body>

	<div class="container">
        <div class="main-list-left">
            <form action="/lists/add" method="POST">
                <!-- CSRF field -->
                <input type="text" class="list-input" name="list_name" id="list_name" autofocus>
            </form>
            <?php if ( count($user->getLists()) == 0 ): ?>
                <span class="empty-lists">There are no lists.</span>
            <?php endif; ?>
            <?php foreach( $user->getLists() as $list ): ?>

            <?php endforeach; ?>
        </div>
        <div class="list-items-right">
        </div>
	</div>

</body>
</html>
