<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="/css/main.css">
</head>
<body>

	<div class="container">

		<!-- list details -->
		<div class="list-header">
			<h3>
				<a href="/list/<?= $item->getList()->getId(); ?>">&lt;&dash;</a>
				<?= $item->getList()->getListName(); ?>
			</h3>
		</div>

		<form action="/item/<?= $item->getId(); ?>/edit" method="POST">
			<!-- csrf field -->
			<input type="text" value="<?= $item->getValue(); ?>" name="item_value" id="item_value" class="list-input">
		</form>
		<a class="list-element list-element-action" href="/item/<?= $item->getId(); ?>/delete">delete</a>
		<a class="list-element list-element-action" href="/item/<?= $item->getId(); ?>/complete">complete</a>
	</div>

</body>
</html>